### ISSUE TITLE
Setting Memcache and other config variables

### ISSUE THREAD

**Issue by simonspa** [nkakouros-original/ansible-role-nextcloud#25]
I was wondering what the best way is to configure a memcache like Redis. I course I could simply add the relevant parameters to `nextcloud_config` but we could also add some logic, exposing the individual configuration parameters and then adding them to nextcloud using `php occ config:set`?

I was thinking of e.g. Redis, mail SMTP etc.

With this we could also add some magic like checking if variables from `geerlinguy.redis` are around and automatically configure it appropriately (`redis_requirepass` etc).

Let me know what you think.

**Comment by nkakouros** [comment]
I had the same dilemma in the past for many other roles as well. I have concluded that the best approach is to handle configuration minimally, even have a "text" variable that will be spat in a config file. Some of the reasons are:

- The user of the role will have in either case (with us exposing the configuration parameters as variables or without) to configure those parameters and make sure they are correct, etc. Having them exposed as separate variables doesn't really add any value to them, in the contrary, they have to keep track of the mapping between the parameters and our variables. Not exposing them, on the other hand, allows them to define their own direct variables and then use them in `nextcloud_config`. For instance, in:

https://github.com/nkakouros-original/ansible-role-nextcloud/blob/6201c7ac8506e2973d68c88af369e7cd5eb4a2bf/molecule/default/playbook.yml#L7-L22

you can see how I do it in my own playbook, where I re-use variables set for other roles (that install apache, mysql) to configure this role. Re-using the redis role's variables could be similar.
- When the configuration options are a lot, the role becomes crowded with variables that do not really add value and make it harder for the user to go through the variables relevant for their case.
- It also adds maintenance overhead that, again, does not add actual value. For each new version of nextcloud, we will have to go through the release notes and check new or removed parameters. While this is great if someone wants to be following all the developments in nextcloud closely, it is not sth a role maintainer should have to do.
- Having the parameters makes it also harder to deal with them in yml. Loops become uglier, eg if you want to loop through all the variables, you will have to list them all or use the ` vars` lookup, adding defaults, conditionals, etc. It will also make any templates longer and harder to read.
- Having parameters in a single variable such as the `nextcloud_config` dict makes it easy to manipulate them (eg merge user config with defauts, loop, ...)
- Also, it is much faster to just dump everything in a file and tell `occ` to import it than looping and using `config:set` for each one of them.
- I also think that having a role replicate part of the logic of the software it installs is not good practice, as yaml is not that expressive, it becomes complicated and it is quite unnecessary. For instance, if some config parameter has to be set if another one is also set, be a string of characters/nums/some-special-characters, point to an actual resource on the system and what-not, I think it is better to let the user handle all this and if they don't, let them see the error from the software at the end of the provisioning process. I mention this here because having parameters exposed as variables implies that such checks could be added too. Of course, for sth simple, such as checking if the user has set a variable that is required both by the software but also by the role tasks that would otherwise fail, it is good to have checks in place.

Of course, if there is a part of the config that could be split out of the general `nextcloud_config` dict to add functionality, we should do this. For example, in [another role of mine](https://github.com/nkakouros-original/ansible-role-elasticsearch), I have a general `config` dict were all the configuraion could go in unconditionally. But I also provide separate variables for a part of the config that handles TLS certificates/keys. This is in addition to the `config` dict. I do this because the role will also have to handle certiicate generation, putting into place, setting permissions, etc. Having them as separate variables make it easier to perform these tasks, check the variable values and expose them as functionality to the user. If I didn't have them as separate variables, I would have to dig into the `config` dict, check if they are there, inform the user, etc.

For the redis configuration, I cannot see how this could be the case, but I could of course be mistaken. For the email part, we could maybe have them exposed as separate variables to add some more value to the user. But I don't know what this could be. I am open and willing to add such logic if it adds value.

About the magic part you mention, I would like to keep the role totally independent from other roles and not promote specific 3rd party roles. As I showed in the snippet above, it is trivial for the user to re-use variables from other roles to configure this role. Adding logic to support 3rrd party roles to make it a tiny little easier for the user is not in my opinion a good investment of resources, plus it adds one more thing that we will need to keep track of for future changes. Leaving it to the user, the playbook is built in a modular way and the user can easily build a chain of roles where a role can be replaced by another, each user taking care of their use case and role ecosystem.
